### ISSUE TITLE
Frigate Notification Beta Version requires Device Name for Mobil Device even if group is used

### ISSUE THREAD

**Issue by MickPBduece** [SgtBatten/HA_blueprints#126] opened 2023-11-23 04:53 UTC
### Description

Frigate Notification Beta Version requires Device Name for Mobil Device even if group is used.  Using group does still trigger the notification to the group 

### Version

0.12.0.1

### Automation Config

```yaml
- id: '1700713820172'
  alias: Frigate (0.12.0.1) Front Door
  description: ''
  use_blueprint:
    path: SgtBatten/Beta.yaml
    input:
      camera: camera.frontdoor
      notify_group: jc_notifier_group
      title: Camera Notif
      message: ' {{camera_name}} detected {{label}}'
      ios_live_view: camera.frontdoor
      tv_transparency: 100%
      tv_duration: 180
      notify_device: 92601ed1284851e0866af8ed0058597b
```

### Frigate Config

```yaml
na
```

### Any other relevant information

```yaml
Not a big deal to me but I did see a change so wanted to make sure it wasn't inadvertant
```

**Comment by jazzcpuguy** [comment] 2023-11-23 17:02
Additional info: I am using 0.12.0.2 verson of the blueprint and got a malformed device error when trying to save automation specifying only a notification group name.  Adding an individual device in addition to the group name enabled the group messaging to work as expected.  I am glad I stumbled onto this error report as it clued me into the workaround.

**Comment by alegeay** [comment] 2023-11-24 23:21
same issue here in version 0.12.0.2

**Comment by SgtBatten** [comment] 2023-11-25 06:31
Duplicate of #112 

Please just select a device, nothing will change.

**Closed by SgtBatten** 2023-11-25 06:31 UTC
Labels: bug
