### ISSUE TITLE
[Feature Request]: Multiple Frigate Camera at the same Automations

### ISSUE THREAD

**Issue by mabed-fr** [SgtBatten/HA_blueprints#144] opened 2023-12-29 15:54 UTC
Hello,

Very good job ! 

It is possible to add multiple or ALL Cam to same automations ?

**Comment by SgtBatten** [comment] 2023-12-30 02:38
Not currently. Perhaps in the future. 

duplicate of #26

**Closed by SgtBatten** 2023-12-30 02:38 UTC
Labels: enhancement
