### ISSUE TITLE
[Config Support]: cant leave "device" blank and use notify group - error when saving

### ISSUE THREAD

**Issue by Menz01** [SgtBatten/HA_blueprints#130] opened 2023-12-02 21:55 UTC
### Describe the problem you are having or the outcome you are trying to achieve.

i created a notify group so i could incluse both my phone and my TV. so i went into the blueprint and added my notify group and then deleted my phone that was in the device line and when i click save i see a popup that says "message malformed: unknown device" and i cant save it. if i put my phone back in device i can save it

### Version

0.12.0.2

### Automation config file

```yaml
not sure what to put here
```

**Comment by SgtBatten** [comment] 2023-12-03 01:37
Thanks, we are aware it is mandatory to fill the device since HA 2023.11

Duplicate of #112

**Closed by SgtBatten** 2023-12-03 01:37 UTC
