### ISSUE TITLE
[Feature Request]: Provide option to trigger additional actions

### ISSUE THREAD

**Issue by bmck0118** [SgtBatten/HA_blueprints#69] opened 2023-08-04 17:02 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to trigger additional actions on run so that I can send a message to google home or turn on a light based on occupacy for example

**Describe the solution you'd like**
Add an extra option to trigger a service / action or even a script in addition to sending a notification

**Describe alternatives you've considered**
Can't think of any while being able to utilise the benefits of this blueprint configuration.  Option used currently is to create a separate automation triggered by the camera occupancy status but that doesn't easily provide the same filtering and options unless they are fully specified manually.

**Additional context**

**Comment by SgtBatten** [comment] 2023-08-04 21:41
There is a seperate branch called custom action. I built in months ago as many people requested this. But no-one is providing feedback on it. 

Please try it and let me know what can be improved for your use case

**Comment by bmck0118** [comment] 2023-08-05 00:04
Perfect. I'll check it out and let you know. Thanks.

**Comment by reesion** [comment] 2023-08-12 23:23
> There is a seperate branch called custom action. I built in months ago as many people requested this. But no-one is providing feedback on it.
> 
> Please try it and let me know what can be improved for your use case

Hi,

I am using the custom action branch but am unable to see the additional options. Am i missing anything?

**Comment by SgtBatten** [comment] 2023-08-13 02:29
Please use the beta

**Comment by SgtBatten** [comment] 2023-08-24 03:54
Any feeback @reesion

**Comment by reesion** [comment] 2023-08-25 09:00
> Any feedback @reesion ?

Hi, unfortunately I am unable to get it to work. I  added a condition for after sunset and before sunrise to trigger a light switch but it doesn’t seem to work.

**Comment by SgtBatten** [comment] 2023-08-25 11:48
> it doesn’t seem to work.

It had been a while since I created it so after reviewing the code, I have reworked it just now. You will see 3 custom action fields now with some guidance

**Comment by SgtBatten** [comment] 2023-08-25 12:21
> Is this the correct url?

https://github.com/SgtBatten/HA_blueprints/blob/custom_action/Frigate%20Camera%20Notifications/Beta

**Comment by reesion** [comment] 2023-08-26 13:07
> https://github.com/SgtBatten/HA_blueprints/blob/custom_action/Frigate%20Camera%20Notifications/Beta

this doesn’t seem to work. I am using the ‘Auto trigger’ and have removed the conditions to eliminate the issue and just put a service Switch: Toggle to turn on a switch but still not working.

**Comment by SgtBatten** [comment] 2023-08-26 22:24
Okay I will try to test soon 

The manual trigger is working for me. Tested that yesterday to toggle a light

**Comment by reesion** [comment] 2023-08-28 05:41
> The manual trigger is working for me. Tested that yesterday to toggle a light

I have tested the manual trigger and can confirm it worked as well. Just couldn't get the 'Auto trigger' working

**Comment by krystiancharubin** [comment] 2023-08-28 12:32
I've also been trying to get auto actions working but they are not triggering. Commented out most of the conditions leaving jus the length condition and it seems to still evaluate to false

```
- alias: "Custom Action Auto"
  choose:
  - conditions:
      - "{{ custom_action_auto |length}}"
      # - "{{ not zone_only or (not zone_multi and zones|select('in', entered_zones)|list|length > 0) or (zone_multi and entered_zones|length > 0 and zones |reject('in', entered_zones) |list |length == 0) }}"
      # - "{{ not initial_home }}"
      # - "{{ not state_only or states(input_entity) in states_filter }}"
    sequence: !input "custom_action_auto"
```

**Comment by SgtBatten** [comment] 2023-08-28 20:18
I haven't had a chance to try yet. When looking at the trace tree and clicking on the conditions step for this does it say condition 0 of false?

**Comment by krystiancharubin** [comment] 2023-08-28 20:23
```
Executed: August 28, 2023 at 7:58:28 AM
Result:
result: false
conditions/0
Executed: August 28, 2023 at 7:58:28 AM
Result:
result: false
entities: []
```

Creating `action_auto` variable from the input and changing the conditions to the following seems to make it enter the branch but it still did not seem to fire the action properly.
```
conditions:
  - '{{ action_auto |length > 0 }}'
```

**Comment by SgtBatten** [comment] 2023-08-28 22:25
Oh I know what it is.

**Comment by SgtBatten** [comment] 2023-08-29 09:04
Updated the custom action branch. 

I have the looped action working fine now implementing a version of your fix @krystiancharubin so thanks.

**Comment by krystiancharubin** [comment] 2023-08-29 19:51
Confirmed the new beta is working. Merging of variables in the custom action appears to work as well.

**Comment by reesion** [comment] 2023-08-29 23:35
Confirmed the new beta is working for me as well. Thank you

**Comment by rroller** [comment] 2023-09-12 01:53
I just tested this, works great and is exactly what I need. Would greatly appreciate it if this was merged back into main. Thanks for this!

**Comment by SgtBatten** [comment] 2023-09-12 03:00
Thanks for the feedback all. Will merge when I get a minute. Hopefully not long

**Comment by rroller** [comment] 2023-09-12 03:22
Does the custom action fire after the notification is sent or before?
I'm asking because I'd like to make sure the custom action is fired as quickly as possible and am wondering if there's any delay currently because of the execution order?

**Comment by SgtBatten** [comment] 2023-09-12 05:24
Before from memory

**Comment by SgtBatten** [comment] 2023-10-04 08:24
closed with #96

**Closed by SgtBatten** 2023-10-04 08:24 UTC
Labels: bug, enhancement

**Comment by rroller** [comment] 2023-10-05 03:53
Looks like there's no new release created?

**Comment by SgtBatten** [comment] 2023-10-06 03:47
The releases don't do anything, it's just a snapshot in time.

**Comment by rroller** [comment] 2023-11-04 18:00
Will this be merged to the stable branch?

**Comment by SgtBatten** [comment] 2023-11-04 20:25
Yes I've been meaning to for a long time. I need to not merge all the beta functions but most are stable now.

**Comment by rroller** [comment] 2023-11-05 05:09
I copied it into my local stable copy and it works fine.
