### ISSUE TITLE
Zone filter

### ISSUE THREAD

**Issue by bregol** [SgtBatten/HA_blueprints#2] opened 2023-04-11 23:19 UTC
I have an alert set up with a filter to only alert for a single zone "zonedriveway".  In the blueprint utilization I have the filter turned on:
```
    zone_filter: true
    zones:
      - zonedriveway
```

However, with a short couple tests, it was not triggering when I entered the zone.  I didn't test thoroughly, but I think it triggered when I left the zone rather than when I entered it.

I was able to get the zone filter to work properly when I enabled the zone_multi option:
```
    zone_filter: true
    zone_multi: true
    zones:
      - zonedriveway
```

Haven't had time to dig more into it, but wanted to share this potential bug.

**Comment by mr-brains** [comment] 2023-04-12 20:49
I just tested this and i have te same.
I get the notify when the movement is over .
With multi zone i get the notify instant.
Al this with 1 zone.

**Comment by SgtBatten** [comment] 2023-04-12 20:59
> I just tested

Can you share a screenshot of the trace tree for the one you just tested

**Comment by SgtBatten** [comment] 2023-04-12 21:27
Observing this also. Something wrong with the filters being applied. I need to fix the condition

**Comment by SgtBatten** [comment] 2023-04-12 21:54
@bregol @mr-brains try 16b

**Comment by mr-brains** [comment] 2023-04-13 10:00
Testing now, looking good but I am not home so my chickens need to movie to test it properly.
Will test some more when i am home.

**Comment by alexlmiller** [comment] 2023-08-04 14:55
Noting that as of 12.0.1 this issue seems to be present again - I had to enable multi-zone to get the zone filter to work, even though there's only one zone on the camera

**Comment by SgtBatten** [comment] 2023-08-04 21:40
Okay I'll have a look at what I fixed in 16b and see what went wrong

**Comment by SgtBatten** [comment] 2023-08-04 21:58
The particular lines of code relevant to this are unchanged. Can someone enable debug and post some outputs where it fails but you don't believe it should

**Comment by alexlmiller** [comment] 2023-08-05 01:06
Attached are screenshots of the debugs I took when I was testing it this
morning

The 8:41 time did not work (and multizone was false)
The 8:52 time did (multizone was true)

Let me know if this is what you need for it or if there's anything else

**Comment by SgtBatten** [comment] 2023-08-17 11:05
@alexlmiller Please test the version at the pull request above.

**Comment by alexlmiller** [comment] 2023-08-17 13:41
@SgtBatten Tested and confirmed working. Here's the YAML for the version working with the beta, the only difference here is whether `zone_multi:` is true or false

```
alias: Frigate // Beta Person on Stairs
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.rear_deck
    notify_group: alex
    base_url: XXXXXXXXXXXXXXX
    message: Person detected on Rear Lower Level Stairs
    alert_once: true
    update_thumbnail: true
    zone_filter: true
    zones:
      - lower_level_stairs
    labels:
      - person
    url_2: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']}}?token={{state_attr(
      'camera.' ~ camera, 'access_token')}}
    button_2: View Live
    url_1: "{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4"
    button_1: View Clip
    tap_action: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    button_3: Silence
    debug: true
    cooldown: 0
    zone_multi: false
```

**Closed** 2023-09-18 11:22 UTC
