### ISSUE TITLE
[Not receiving Notification]: Not receiving notification on IOS mobile

### ISSUE THREAD

**Issue by Frazou1** [SgtBatten/HA_blueprints#162] opened 2024-02-12 21:21 UTC
### Description

Just setup the last stable version of Blueprint for notification and i dont receive any notification but i see the automation fired

### Version

12.0.2

### Automation Config

```yaml
alias: Notif-Cam_Arriere
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.cam_ext_arriere
    notify_device: 719c7bb8a919fd359eee8bcbf3d50dad
    base_url: https://frazhome.zapto.org
    message: "{{ label }} detected - {{ camera_name }}"
    alert_once: true
    attachment: snapshot
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    ios_live_view: true
    zone_filter: true
    labels:
      - person
    critical: "true"
```

**Comment by SgtBatten** [comment] 2024-02-14 00:44
try disabling zone filter. you have it enabled but no zones defined

**Comment by Frazou1** [comment] 2024-02-14 10:43
I have the same results. Automation fired but nothing on my phone. I have other automation without blueprints to notify me snd that one works fine

**Comment by SgtBatten** [comment] 2024-02-14 20:41
Show me a screenshot of the visual representation of the trace (trace tree)

**Comment by Frazou1** [comment] 2024-02-16 15:18
I reset my frigate config, my phone integration and now i receiving notification. The only thing they remain is when i click on it. They doesnt show me the image or video. Just see : {"message":"Event not found","success":false}

**Comment by SgtBatten** [comment] 2024-02-18 19:38
> They doesnt show me the image or video. Just see : {"message":"Event not found","success":false}

What says this?

If in a browser, what is the url?

**Comment by cullorblind** [comment] 2024-06-13 03:47
I had the same problem (except mine is on Android) of not getting push notifications when the Filter was enabled and Object Filter was set to anything.  eg. person.
Adding a zone fixed mine. Now I can get person notifications without the cat highway across my front porch annoying me all day.

**Comment by SgtBatten** [comment] 2024-06-14 11:18
@cullorblind please open a new issue. 
 
 This one is ios specific
 Duplicate of  #45

**Closed by SgtBatten** 2024-06-14 11:18 UTC
